### ISSUE TITLE
Need . netstandard2.0

### ISSUE THREAD

**Issue by hqzzzz** [Baseflow/DSTV.Net#7]
https://dotnet.microsoft.com/zh-cn/platform/dotnet-standard#versions

Can you provide. NET Standard  to run in more places.

**Comment by martijn00** [comment]
Why do you need this? Is there a case .NET6 is not sufficient enough?

**Comment by tluijken** [comment]
I understand the need for the .net standard runtime, as the domain where this package is typically used, still relies on .NET Framework 4.x.x heavily.

Please review changes made to the netstandard20 branch. When approved, the nuget package with support for .NET Standard 2.0 will be available soon after merging.

**Comment by tluijken** [comment]
@hqzzzz a netstandard runtime version has been made available in version [1.2.0](https://github.com/Baseflow/DSTV.Net/releases/tag/v1.2.0). 

Supported framework versions are listed [here](https://www.nuget.org/packages/DSTV.Net#supportedframeworks-body-tab)

Thank you for reporting this issue.
